[
  {
    id: 'price_1PWC7H2eZvKYlo2Cv8OpAMUL',
    object: 'price',
    active: true,
    billing_scheme: 'per_unit',
    created: 1719470855,
    currency: 'usd',
    custom_unit_amount: null,
    livemode: false,
    lookup_key: null,
    metadata: {},
    nickname: null,
    product: 'prod_QMvzCgLU1mYaVR',
    recurring: null,
    tax_behavior: 'unspecified',
    tiers_mode: null,
    transform_quantity: null,
    type: 'one_time',
    unit_amount: 1000,
    unit_amount_decimal: '1000'
  },
  {
    id: 'price_1PWACn2eZvKYlo2C4UZiO1Yq',
    object: 'price',
    active: true,
    billing_scheme: 'per_unit',
    created: 1719463509,
    currency: 'usd',
    custom_unit_amount: null,
    livemode: false,
    lookup_key: null,
    metadata: {},
    nickname: null,
    product: 'prod_QMu0SypMZStiQ4',
    recurring: null,
    tax_behavior: 'unspecified',
    tiers_mode: null,
    transform_quantity: null,
    type: 'one_time',
    unit_amount: 1000,
    unit_amount_decimal: '1000'
  },
  {
    id: 'price_1PW9u72eZvKYlo2CysGSkvBu',
    object: 'price',
    active: true,
    billing_scheme: 'per_unit',
    created: 1719462351,
    currency: 'usd',
    custom_unit_amount: null,
    livemode: false,
    lookup_key: null,
    metadata: {},
    nickname: null,
    product: 'prod_QMthYoZQOX6Sip',
    recurring: null,
    tax_behavior: 'unspecified',
    tiers_mode: null,
    transform_quantity: null,
    type: 'one_time',
    unit_amount: 1000,
    unit_amount_decimal: '1000'
  },
  {
    id: 'price_1PW9K92eZvKYlo2CRwvnPM9Q',
    object: 'price',
    active: true,
    billing_scheme: 'per_unit',
    created: 1719460121,
    currency: 'usd',
    custom_unit_amount: null,
    livemode: false,
    lookup_key: null,
    metadata: [Object],
    nickname: null,
    product: 'prod_QMt6ZG4rnqmpaa',
    recurring: [Object],
    tax_behavior: 'unspecified',
    tiers_mode: null,
    transform_quantity: null,
    type: 'recurring',
    unit_amount: 638804,
    unit_amount_decimal: '638804'
  },
  {
    id: 'price_1PW6xw2eZvKYlo2CMDYuO7sP',
    object: 'price',
    active: true,
    billing_scheme: 'per_unit',
    created: 1719451056,
    currency: 'usd',
    custom_unit_amount: null,
    livemode: false,
    lookup_key: null,
    metadata: {},
    nickname: null,
    product: 'prod_QMqeWMZQup7wLS',
    recurring: [Object],
    tax_behavior: 'unspecified',
    tiers_mode: null,
    transform_quantity: null,
    type: 'recurring',
    unit_amount: 999,
    unit_amount_decimal: '999'
  },
  {
    id: 'price_1PW6xS2eZvKYlo2C0mLz2Qx8',
    object: 'price',
    active: true,
    billing_scheme: 'per_unit',
    created: 1719451026,
    currency: 'usd',
    custom_unit_amount: null,
    livemode: false,
    lookup_key: null,
    metadata: {},
    nickname: null,
    product: 'prod_QMqeWMZQup7wLS',
    recurring: [Object],
    tax_behavior: 'unspecified',
    tiers_mode: null,
    transform_quantity: null,
    type: 'recurring',
    unit_amount: 9999,
    unit_amount_decimal: '9999'
  },
  {
    id: 'price_1PW48t2eZvKYlo2CVubVkBs4',
    object: 'price',
    active: true,
    billing_scheme: 'per_unit',
    created: 1719440203,
    currency: 'usd',
    custom_unit_amount: null,
    livemode: false,
    lookup_key: null,
    metadata: {},
    nickname: null,
    product: 'prod_QMnkTtMUzQpMDl',
    recurring: [Object],
    tax_behavior: 'unspecified',
    tiers_mode: null,
    transform_quantity: null,
    type: 'recurring',
    unit_amount: 1999,
    unit_amount_decimal: '1999'
  },
  {
    id: 'price_1PW48s2eZvKYlo2C5Xs6ANwR',
    object: 'price',
    active: true,
    billing_scheme: 'per_unit',
    created: 1719440202,
    currency: 'usd',
    custom_unit_amount: null,
    livemode: false,
    lookup_key: null,
    metadata: {},
    nickname: null,
    product: 'prod_QMnk5Qk8WB52eB',
    recurring: [Object],
    tax_behavior: 'unspecified',
    tiers_mode: null,
    transform_quantity: null,
    type: 'recurring',
    unit_amount: 2999,
    unit_amount_decimal: '2999'
  },
  {
    id: 'price_1PW48s2eZvKYlo2CDlcEuTZ5',
    object: 'price',
    active: true,
    billing_scheme: 'per_unit',
    created: 1719440202,
    currency: 'usd',
    custom_unit_amount: null,
    livemode: false,
    lookup_key: null,
    metadata: {},
    nickname: null,
    product: 'prod_QMnkSMCi8pbk33',
    recurring: [Object],
    tax_behavior: 'unspecified',
    tiers_mode: null,
    transform_quantity: null,
    type: 'recurring',
    unit_amount: 3599,
    unit_amount_decimal: '3599'
  },
  {
    id: 'price_1PW4752eZvKYlo2ChvO5PKoU',
    object: 'price',
    active: true,
    billing_scheme: 'per_unit',
    created: 1719440091,
    currency: 'usd',
    custom_unit_amount: null,
    livemode: false,
    lookup_key: null,
    metadata: {},
    nickname: null,
    product: 'prod_QMniM3j6vQ5ybB',
    recurring: [Object],
    tax_behavior: 'unspecified',
    tiers_mode: null,
    transform_quantity: null,
    type: 'recurring',
    unit_amount: 1999,
    unit_amount_decimal: '1999'
  }
]